package view;

import controller.ProdutoDaoDef;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.ProdutoDef;

/**
 *
 * @author Inacio
 */
public class FormCadProdutoDef extends javax.swing.JDialog {

    public ResultSet resul;

    /**
     * Creates new form FormCadastroDef
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public FormCadProdutoDef(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.carregarProduto();
        this.camposBotoesInicioCadastro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnBase = new javax.swing.JPanel();
        lblTitleCadastro = new javax.swing.JLabel();
        lblIdProduto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblQt = new javax.swing.JLabel();
        lblVlCompra = new javax.swing.JLabel();
        lblIcms = new javax.swing.JLabel();
        lblVlVenda = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        textIdProduto = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        textProduto = new javax.swing.JTextField();
        textTpProduto = new javax.swing.JTextField();
        textQtProduto = new javax.swing.JTextField();
        textVlCompraProd = new javax.swing.JTextField();
        textIcmsProd = new javax.swing.JTextField();
        textVlVendaProd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnBase.setBackground(new java.awt.Color(0, 68, 111));
        jpnBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 60, 0), 5));
        jpnBase.setPreferredSize(new java.awt.Dimension(715, 265));
        jpnBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCadastro.setText("<html><font size = 6><b><u>Cadastro Produto</b></u></font></html>");
        lblTitleCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnBase.add(lblTitleCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, -1));

        lblIdProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProduto.setText("ID");
        jpnBase.add(lblIdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 54, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("CATEGORIA");
        jpnBase.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 54, -1, -1));

        lblProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblProduto.setText("PRODUTO");
        jpnBase.add(lblProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 104, -1, -1));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("TIPO");
        jpnBase.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 104, -1, -1));

        lblQt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQt.setForeground(new java.awt.Color(255, 255, 255));
        lblQt.setText("QUANTIDADE");
        lblQt.setRequestFocusEnabled(false);
        jpnBase.add(lblQt, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 154, -1, -1));

        lblVlCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVlCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblVlCompra.setText("VALOR DE COMPRA");
        lblVlCompra.setRequestFocusEnabled(false);
        jpnBase.add(lblVlCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 154, -1, -1));

        lblIcms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIcms.setForeground(new java.awt.Color(255, 255, 255));
        lblIcms.setText("ICMS");
        jpnBase.add(lblIcms, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 204, -1, -1));

        lblVlVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVlVenda.setForeground(new java.awt.Color(255, 255, 255));
        lblVlVenda.setText("VALOR DE VENDA");
        jpnBase.add(lblVlVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 204, -1, -1));

        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jpnBase.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 25));

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jpnBase.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 90, 25));

        btnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluirMouseClicked(evt);
            }
        });
        jpnBase.add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 25));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpnBase.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 25));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jpnBase.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 25));

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jpnBase.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 25));
        jpnBase.add(textIdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 60, 25));

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Administrador", "Usuário"}));
        jpnBase.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 144, 25));

        textProduto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jpnBase.add(textProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 340, 25));
        jpnBase.add(textTpProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 144, -1));
        jpnBase.add(textQtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 25));

        textVlCompraProd.setVerifyInputWhenFocusTarget(false);
        jpnBase.add(textVlCompraProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 144, 25));
        jpnBase.add(textIcmsProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));
        jpnBase.add(textVlVendaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 144, 25));

        getContentPane().add(jpnBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 380));

        jPanel2.setBackground(new java.awt.Color(255, 60, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblProduto.setAutoCreateRowSorter(true);
        tblProduto.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categoria", "Produto", "Tipo", "Quantidade", "Vl Compra", "ICMS", "Vl Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProduto.setAutoscrolls(false);
        tblProduto.setColumnSelectionAllowed(true);
        tblProduto.setGridColor(new java.awt.Color(255, 255, 255));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        tblProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProdutoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduto);
        tblProduto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblProduto.getColumnModel().getColumnCount() > 0) {
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProduto.getColumnModel().getColumn(1).setPreferredWidth(75);
            tblProduto.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblProduto.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblProduto.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblProduto.getColumnModel().getColumn(6).setPreferredWidth(40);
            tblProduto.getColumnModel().getColumn(7).setPreferredWidth(80);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 730, 215));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 740, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        this.clickJtable();
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void tblProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutoKeyPressed
        this.clickJtable();
    }//GEN-LAST:event_tblProdutoKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        formWindowOpened();
    }//GEN-LAST:event_formWindowOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.sairProduto();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluirProduto();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked
        this.cadastrarProduto();//Cadastra
    }//GEN-LAST:event_btnIncluirMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.novoProduto();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.pesquisarProduto();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.alterarProduto();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadProdutoDef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadProdutoDef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadProdutoDef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadProdutoDef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadProdutoDef dialogProd = new FormCadProdutoDef(new javax.swing.JFrame(), true);
                dialogProd.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialogProd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnBase;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIcms;
    private javax.swing.JLabel lblIdProduto;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQt;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitleCadastro;
    private javax.swing.JLabel lblVlCompra;
    private javax.swing.JLabel lblVlVenda;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField textIcmsProd;
    private javax.swing.JTextField textIdProduto;
    private javax.swing.JTextField textProduto;
    private javax.swing.JTextField textQtProduto;
    private javax.swing.JTextField textTpProduto;
    private javax.swing.JTextField textVlCompraProd;
    private javax.swing.JTextField textVlVendaProd;
    // End of variables declaration//GEN-END:variables

    private void carregarProduto() {
        //centraliza o cabeçalho da table
        ((DefaultTableCellRenderer) tblProduto.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableModel mytbmodel = (DefaultTableModel) tblProduto.getModel();
        ProdutoDaoDef u1 = new ProdutoDaoDef();

        resul = u1.buscartodos();
        try {
            // apaga todas as linhas do Jtable
            while (tblProduto.getModel().getRowCount() > 0) {
                ((DefaultTableModel) tblProduto.getModel()).removeRow(0);
            }

            while (resul.next()) {
                Object[] linhas = {
                    resul.getInt("IdProduto"),
                    resul.getInt("Fk_idCategoria"),
                    resul.getString("produto"),
                    resul.getString("tipo"),
                    resul.getInt("quantidade"),
                    resul.getFloat("vlCompra"),
                    resul.getFloat("icms"),
                    resul.getFloat("vlVenda")};

                // adiciona uma linha de cada vez no jtable de usua?ios
                mytbmodel.addRow(linhas);
            }

            // posiciona o focus no campo 
            this.textProduto.grabFocus();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar produto\n" + err.getMessage());
        }
    }

    private void formWindowOpened() {
        // captura o modelo do combobox para inserir itens
        DefaultComboBoxModel obj;
        obj = (DefaultComboBoxModel) this.cmbCategoria.getModel();
        obj.removeAllElements(); // remove todos os elementos do combobox
        obj.addElement(""); // adiciona o primeiro elemento vazio
        obj.addElement("Alvenaria"); // adiciona o item operador
        obj.addElement("Acabamento"); // adiciona o item gerente

        //carregarProduto(); // chama o método carregar_usuarios para preencher o jtable
    }

    //Funções para os botões - INÍCIO
    private void novoProduto() {
        //ativa os campos
        this.limparCampos();
        this.camposBotoesNovoProduto();
    }

    private void cadastrarProduto() {
        //Instancia a Classe "UsuarioDef" e cria o objeto "Lu" - Pacote "Model"
        ProdutoDef cad = new ProdutoDef();

        //usa o objeto "cad" para adiconar os valores na classe "ProdutoDef" - Pacote "Model"            
        cad.setFk_idCategoria(this.cmbCategoria.getSelectedIndex());
        cad.setProduto(this.textProduto.getText());
        cad.setTipo(this.textTpProduto.getText());
        cad.setQuantidade(Integer.parseInt(this.textQtProduto.getText()));
        cad.setVlCompra(Float.parseFloat(this.textVlCompraProd.getText()));
        cad.setIcms(Float.parseFloat(this.textIcmsProd.getText()));
        cad.setVlVenda(Float.parseFloat(this.textVlVendaProd.getText()));

        //Instancia a Classe "UsuarioDaoDef"
        ProdutoDaoDef u1 = new ProdutoDaoDef();
        //executa a função "incluir" da classe "UsuarioDaoDef"        
        u1.incluir(cad);// se não existir chama o u1.incluir()
        this.carregarProduto();
        this.camposBotoesInicioCadastro();

        this.limparCampos();
        this.textProduto.grabFocus(); //coloca o cursor no campo nome        
    }

    private void alterarProduto() {
        //Instancia a Classe "UsuarioDef" e cria o objeto "Lu" - Pacote "Model"
        ProdutoDef cad = new ProdutoDef();

        //usa o objeto "cad" para adiconar os valores na classe "ProdutoDef" - Pacote "Model"    
        cad.setIdProduto(Integer.parseInt(this.textIdProduto.getText()));
        cad.setFk_idCategoria(this.cmbCategoria.getSelectedIndex());
        cad.setProduto(this.textProduto.getText());
        cad.setTipo(this.textTpProduto.getText());
        cad.setQuantidade(Integer.parseInt(this.textQtProduto.getText()));
        cad.setVlCompra(Float.parseFloat(this.textVlCompraProd.getText()));
        cad.setIcms(Float.parseFloat(this.textIcmsProd.getText()));
        cad.setVlVenda(Float.parseFloat(this.textVlVendaProd.getText()));

        //Instancia a Classe "UsuarioDaoDef"
        ProdutoDaoDef u1 = new ProdutoDaoDef();
        //executa a função "incluir" da classe "UsuarioDaoDef"
        /* Para verificar se o usuário existe buscamos o id primeiro */
        resul = u1.buscar(cad);
        try {
            if (resul.next()) {
                u1.alterar(cad);// caso exista chama u1.alterar()
                this.carregarProduto();
                this.camposBotoesInicioCadastro();
            } else {
                this.camposBotoesInicioCadastro();
                btnEditar.setEnabled(false);
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao Cadastrar Produto!\n" + err.getMessage());
        }

        this.limparCampos();
        this.textProduto.grabFocus(); //coloca o cursor no campo nome        
    }

    private void excluirProduto() {
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente excluir o registro?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (i == 0) {
            ProdutoDaoDef u = new ProdutoDaoDef();
            u.excluir(textIdProduto.getText());
            
            this.limparCampos();
            this.textProduto.grabFocus(); //coloca o cursor no campo cpf
            this.carregarProduto();
        }
    }

    private void pesquisarProduto() {
        // instancia a classe UsuarioProj model
        ProdutoDef obj = new ProdutoDef();
        obj.setIdProduto(Integer.parseInt(this.textIdProduto.getText()));
        ProdutoDaoDef u1 = new ProdutoDaoDef();
        resul = u1.buscar(obj);
        try {
            if (resul.next()) {
                // se o registro foi encontrado preenche os campos do formulário CadProdutoDef
                this.cmbCategoria.setSelectedIndex(resul.getInt("fk_idCategoria"));
                this.textProduto.setText(resul.getString("produto"));
                this.textTpProduto.setText(resul.getString("tipo"));
                this.textQtProduto.setText(String.valueOf(resul.getInt("quantidade")));
                this.textVlCompraProd.setText(String.valueOf(resul.getFloat("vlCompra")));
                this.textIcmsProd.setText(String.valueOf(resul.getFloat("icms")));
                this.textVlVendaProd.setText(String.valueOf(resul.getFloat("vlVenda")));

                this.botoesPesquisarProduto();

            } else {
                // se não encontrar manda mensagem abaixo
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.limparCampos();
                this.textIdProduto.grabFocus();
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    private void clickJtable() {
        // busca a linha selecionada no jTable1
        int linhasel = this.tblProduto.getSelectedRow();
        int colunachave = 0; // configura coluna como 0, isto é, a primeira coluna
        Object chave = this.tblProduto.getModel().getValueAt(linhasel, colunachave);

        ProdutoDef obj = new ProdutoDef();
        obj.setIdProduto((int) chave);
        ProdutoDaoDef u1 = new ProdutoDaoDef();
        resul = u1.buscar(obj);
        try {
            if (resul.next()) {
                this.textIdProduto.setText(String.valueOf(resul.getInt("idProduto")));
                this.cmbCategoria.setSelectedIndex(resul.getInt("fk_idCategoria"));
                this.textProduto.setText(resul.getString("produto"));
                this.textTpProduto.setText(resul.getString("tipo"));
                this.textQtProduto.setText(String.valueOf(resul.getInt("quantidade")));
                this.textVlCompraProd.setText(String.valueOf(resul.getFloat("vlCompra")));
                this.textIcmsProd.setText(String.valueOf(resul.getFloat("icms")));
                this.textVlVendaProd.setText(String.valueOf(resul.getFloat("vlVenda")));

                this.camposBotoesClickJtable();
            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.limparCampos();
                this.textIdProduto.grabFocus();
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao navegar na Jtable! ");
        }
    }

    private void sairProduto() {
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (i == 0) {
            dispose();
        }
    }
    //Funções para os botões - FIM

    public void limparCampos() {
        this.textIdProduto.setText(""); //limpar
        this.cmbCategoria.setSelectedIndex(0); // limpar
        this.textProduto.setText(""); // limpar
        this.textTpProduto.setText(""); // limpar
        this.textQtProduto.setText(""); // limpar
        this.textVlCompraProd.setText(""); // limpar        
        this.textIcmsProd.setText(""); // limpar
        this.textVlVendaProd.setText(""); // limpar
    }

    public void camposBotoesNovoProduto() {
        this.textIdProduto.setEnabled(false);
        this.cmbCategoria.setEnabled(true);
        this.textProduto.setEnabled(true);
        this.textTpProduto.setEnabled(true);
        this.textQtProduto.setEnabled(true);
        this.textVlCompraProd.setEnabled(true);
        this.textIcmsProd.setEnabled(true);
        this.textVlVendaProd.setEnabled(true);

        this.textProduto.grabFocus(); //coloca o cursor no campo

        //ativa os botões        
        btnIncluir.setEnabled(true);
        btnSair.setEnabled(true);

        //desativa os botões  
        btnPesquisar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        this.carregarProduto();
    }

    public void botoesPesquisarProduto() {
        //ativa os botões 
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnIncluir.setEnabled(true);
        btnEditar.setEnabled(true);
        btnSair.setEnabled(true);
        btnPesquisar.setEnabled(true);
    }

    public void camposBotoesClickJtable() {
        this.todosCamposAtivos();
        this.textIdProduto.setEnabled(false);
        this.textProduto.grabFocus(); //coloca o cursor no campo

        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);

        btnIncluir.setEnabled(false);
        btnPesquisar.setEnabled(false);
    }

    public void todosCamposAtivos() {
        this.textIdProduto.setEnabled(true);
        this.cmbCategoria.setEnabled(true);
        this.textProduto.setEnabled(true);
        this.textTpProduto.setEnabled(true);
        this.textQtProduto.setEnabled(true);
        this.textVlCompraProd.setEnabled(true);
        this.textIcmsProd.setEnabled(true);
        this.textVlVendaProd.setEnabled(true);

        //this.textCpf.grabFocus(); //coloca o cursor no campo cpf
    }

    public void camposBotoesInicioCadastro() {
        //campos
        this.textIdProduto.setEnabled(true);
        this.cmbCategoria.setEnabled(false);
        this.textProduto.setEnabled(false);
        this.textTpProduto.setEnabled(false);
        this.textQtProduto.setEnabled(false);
        this.textVlCompraProd.setEnabled(false);
        this.textIcmsProd.setEnabled(false);
        this.textVlVendaProd.setEnabled(false);

        //botões
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnSair.setEnabled(true);

        btnEditar.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnExcluir.setEnabled(false);

        this.textIdProduto.grabFocus(); //coloca o cursor no campo cpf
    }

    public void todosBotoesAtivos() {
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnIncluir.setEnabled(true);
        btnPesquisar.setEnabled(true);        
        btnExcluir.setEnabled(true);
        btnSair.setEnabled(true);
    }

}
