package view;

import controller.ConectarDaoDefNew;
import controller.UsuarioDaoDefNew;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.UsuarioDefNew;

/**
 *
 * @author Inacio
 */
public final class NewTelaCadUserFull extends javax.swing.JInternalFrame {

    ConectarDaoDefNew conecta = new ConectarDaoDefNew();
    UsuarioDaoDefNew objContDao = new UsuarioDaoDefNew();
    UsuarioDefNew objMod = new UsuarioDefNew();

    /**
     * Creates new form NewTelaCadUser
     */
    public NewTelaCadUserFull() {
        initComponents();        
        camposBotoesInicioCadastro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        textCpf = new javax.swing.JFormattedTextField();
        lblTpUser = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        textCelular = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        textSenha = new javax.swing.JPasswordField();
        textRua = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        lblNumRua = new javax.swing.JLabel();
        textNumRua = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        textComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        textBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        textEstado = new javax.swing.JTextField();
        btnUserNew = new javax.swing.JButton();
        btnUserRegister = new javax.swing.JButton();
        btnUserSearch = new javax.swing.JButton();
        btnUserEdit = new javax.swing.JButton();
        btnUserDel = new javax.swing.JButton();
        lblCpObrigatorios = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Usu·rios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 68, 111));
        jPanel1.setPreferredSize(new java.awt.Dimension(727, 577));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(255, 255, 255));
        lblCpf.setText("*CPF:");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 25, -1, -1));

        try {
            textCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(textCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 160, 25));

        lblTpUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTpUser.setForeground(new java.awt.Color(255, 255, 255));
        lblTpUser.setText("*PERFIL");
        jPanel1.add(lblTpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 25, -1, -1));

        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usu·rio" }));
        jPanel1.add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 40, 144, 25));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("*NOME:");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 88, -1, -1));

        textNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNomeKeyTyped(evt);
            }
        });
        jPanel1.add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 105, 340, 25));

        lblCelular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("*CELULAR:");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 88, -1, -1));

        try {
            textCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(textCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 105, 144, 25));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("*EMAIL:");
        lblEmail.setRequestFocusEnabled(false);
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 154, -1, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        textEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEmailKeyTyped(evt);
            }
        });
        jPanel1.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 340, 25));

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("*SENHA:");
        lblSenha.setRequestFocusEnabled(false);
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 154, -1, -1));
        jPanel1.add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 170, 144, 25));

        textRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textRuaKeyTyped(evt);
            }
        });
        jPanel1.add(textRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 235, 440, 25));

        lblRua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRua.setForeground(new java.awt.Color(255, 255, 255));
        lblRua.setText("*RUA");
        jPanel1.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 218, -1, -1));

        lblNumRua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumRua.setForeground(new java.awt.Color(255, 255, 255));
        lblNumRua.setText("*N∫");
        jPanel1.add(lblNumRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 218, -1, -1));

        textNumRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumRuaKeyTyped(evt);
            }
        });
        jPanel1.add(textNumRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 235, 80, 25));

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(255, 255, 255));
        lblComplemento.setText("COMPLEMENTO");
        jPanel1.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 283, -1, -1));

        textComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textComplementoKeyTyped(evt);
            }
        });
        jPanel1.add(textComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, 25));

        lblBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(255, 255, 255));
        lblBairro.setText("*BAIRRO");
        jPanel1.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 283, -1, -1));

        textBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBairroKeyTyped(evt);
            }
        });
        jPanel1.add(textBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 380, 25));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCidade.setText("*CIDADE");
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 347, -1, -1));

        textCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCidadeKeyTyped(evt);
            }
        });
        jPanel1.add(textCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 365, 440, 25));

        lblUf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUf.setForeground(new java.awt.Color(255, 255, 255));
        lblUf.setText("*ESTADO");
        jPanel1.add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 347, -1, -1));

        textEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEstadoKeyTyped(evt);
            }
        });
        jPanel1.add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 365, 80, 25));

        btnUserNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/create.png"))); // NOI18N
        btnUserNew.setToolTipText("Novo");
        btnUserNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserNew.setName(""); // NOI18N
        btnUserNew.setPreferredSize(new java.awt.Dimension(75, 75));
        btnUserNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserNewMouseClicked(evt);
            }
        });
        btnUserNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        btnUserRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnUserRegister.setToolTipText("Cadastrar");
        btnUserRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserRegister.setName(""); // NOI18N
        btnUserRegister.setPreferredSize(new java.awt.Dimension(75, 75));
        btnUserRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserRegisterMouseClicked(evt);
            }
        });
        btnUserRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 430, -1, -1));

        btnUserSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/read.png"))); // NOI18N
        btnUserSearch.setToolTipText("Consultar");
        btnUserSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserSearch.setPreferredSize(new java.awt.Dimension(75, 75));
        btnUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 430, -1, -1));

        btnUserEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUserEdit.setToolTipText("Editar");
        btnUserEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserEdit.setPreferredSize(new java.awt.Dimension(75, 75));
        btnUserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 430, -1, -1));

        btnUserDel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUserDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnUserDel.setToolTipText("Excluir");
        btnUserDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserDel.setPreferredSize(new java.awt.Dimension(75, 75));
        btnUserDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 430, -1, -1));

        lblCpObrigatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCpObrigatorios.setForeground(new java.awt.Color(255, 255, 255));
        lblCpObrigatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpObrigatorios.setText("*Campos ObrigatÛrios");
        lblCpObrigatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCpObrigatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 725, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        setBounds(0, 0, 740, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSearchActionPerformed
        pesquisarUsers();
    }//GEN-LAST:event_btnUserSearchActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void btnUserNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserNewMouseClicked

    }//GEN-LAST:event_btnUserNewMouseClicked

    private void btnUserEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserEditActionPerformed
        alterarUsers();//altera cadastro existente
    }//GEN-LAST:event_btnUserEditActionPerformed

    private void btnUserDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDelActionPerformed
        excluirUsers();
    }//GEN-LAST:event_btnUserDelActionPerformed

    private void textNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomeKeyTyped
        String caracter = "ABC«DEFGHIJKLMNOPQRSTUVXZWY_-¡¬√… Õ”‘’⁄ ";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textNomeKeyTyped

    private void textEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEmailKeyTyped
        String caracter = "abcdefghijklmnopqrstuvxzwy_-.@0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textEmailKeyTyped

    private void textRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRuaKeyTyped
        String caracter = "ABC«DEFGHIJKLMNOPQRSTUVXZWY_-¡¬√… Õ”‘’⁄. 0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textRuaKeyTyped

    private void textNumRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumRuaKeyTyped
        String caracter = "0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textNumRuaKeyTyped

    private void textComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textComplementoKeyTyped
        String caracter = "ABC«DEFGHIJKLMNOPQRSTUVXZWY_-¡¬√… Õ”‘’⁄. 0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textComplementoKeyTyped

    private void textBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBairroKeyTyped
        String caracter = "ABC«DEFGHIJKLMNOPQRSTUVXZWY_-¡¬√… Õ”‘’⁄. 0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textBairroKeyTyped

    private void textCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCidadeKeyTyped
        String caracter = "ABC«DEFGHIJKLMNOPQRSTUVXZWY_-¡¬√… Õ”‘’⁄. 0123456789";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textCidadeKeyTyped

    private void textEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEstadoKeyTyped
        String caracter = "ABCDEFGHIJKLMNOPQRSTUVXZWY";
        if (!caracter.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_textEstadoKeyTyped

    private void btnUserRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserRegisterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserRegisterMouseClicked

    private void btnUserNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserNewActionPerformed
        btnUserNew();
    }//GEN-LAST:event_btnUserNewActionPerformed

    private void btnUserRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegisterActionPerformed
        cadastrarUsers(); //realiza o cadastro incial
    }//GEN-LAST:event_btnUserRegisterActionPerformed

    private void textNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomeKeyPressed
        //desativa bot„o btnUserSearch
    }//GEN-LAST:event_textNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnUserDel;
    public static javax.swing.JButton btnUserEdit;
    private javax.swing.JButton btnUserNew;
    private javax.swing.JButton btnUserRegister;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpObrigatorios;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumRua;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTpUser;
    private javax.swing.JLabel lblUf;
    private javax.swing.JTextField textBairro;
    private javax.swing.JFormattedTextField textCelular;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textComplemento;
    public static javax.swing.JFormattedTextField textCpf;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumRua;
    private javax.swing.JTextField textRua;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables

    //FunÁıes para os botıes - INÕCIO   
    private void btnUserNew() {
        limparCampos();
        todosCamposAtivos();
        botoesBtnUserNew();
    }

    private void cadastrarUsers() {
        //Instancia a Classe "UsuarioProj" e cria o objeto "Lu" - Pacote "Model"
        //UsuarioDefNew cad = new UsuarioDefNew();

        /*usa o objeto "objMod" para adiconar os valores na classe "UsuarioDefNew" - Pacote "Model"*/
        objMod.setCpf(textCpf.getText());
        objMod.setPerfil((String) cmbPerfil.getSelectedItem());
        objMod.setNome(textNome.getText());
        objMod.setCelular(textCelular.getText());
        objMod.setEmail(textEmail.getText());
        objMod.setSenha(textSenha.getText());
        objMod.setRua(textRua.getText());
        objMod.setNumero(textNumRua.getText());
        objMod.setComplemento(textComplemento.getText());
        objMod.setBairro(textBairro.getText());
        objMod.setCidade(textCidade.getText());
        objMod.setEstado(textEstado.getText());

        if (textCpf.getText().isEmpty() || textNome.getText().isEmpty() || textCelular.getText().isEmpty()
                || textEmail.getText().isEmpty() || textSenha.getText().isEmpty() || textRua.getText().isEmpty()
                || textNumRua.getText().isEmpty() || textBairro.getText().isEmpty() || textCidade.getText().isEmpty()
                || textEstado.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatÛrios!");

        } else {
            //executa a funÁ„o "incluir" da classe "UsuarioDaoDefNew"
            objContDao.incluir(objMod);// chama a funÁ„o incluir da classe UsuarioDaoDefNew

            camposBotoesInicioCadastro();
            //this.limparCampos();
        }
    }

    private void alterarUsers() {
        /*usa o objeto "objMod" para adiconar os valores na classe "UsuarioDefNew" - Pacote "Model"*/
        objMod.setCpf(textCpf.getText());
        objMod.setPerfil((String) cmbPerfil.getSelectedItem());
        objMod.setNome(textNome.getText());
        objMod.setCelular(textCelular.getText());
        objMod.setEmail(textEmail.getText());
        objMod.setSenha(textSenha.getText());
        objMod.setRua(textRua.getText());
        objMod.setNumero(textNumRua.getText());
        objMod.setComplemento(textComplemento.getText());
        objMod.setBairro(textBairro.getText());
        objMod.setCidade(textCidade.getText());
        objMod.setEstado(textEstado.getText());

        //executa a funÁ„o "incluir" da classe "UsuarioDaoProj"
        /* Para verificar se o usu·rio existe buscamos o cpf primeiro */
        conecta.rs = objContDao.buscar(objMod);
        try {
            if (conecta.rs.next()) {
                if (textCpf.getText().isEmpty() || textNome.getText().isEmpty() || textCelular.getText().isEmpty()
                        || textEmail.getText().isEmpty() || textSenha.getText().isEmpty() || textRua.getText().isEmpty()
                        || textNumRua.getText().isEmpty() || textBairro.getText().isEmpty() || textCidade.getText().isEmpty()
                        || textEstado.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha os campos obrigatÛrios!");

                } else { // caso exista chama a funÁ„o alterar()
                    objContDao.alterar(objMod);
                    camposBotoesInicioCadastro();

                }
            } else {
                Object[] options = {"Sim", "N„o"};
                int exUser = JOptionPane.showOptionDialog(null, "Usu·rio n„o cadastrado!\nDeseja fazer o cadastro?", "Aviso",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                        null, options, options[0]);
                if (exUser == 0) {
                    todosCamposAtivos();
                    botoesBtnUserRegister();
                    textCpf.grabFocus();
                    //this.carregarUsers();
                }
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao Alterar Users!\n" + err.getMessage());

            camposBotoesInicioCadastro();
        }
    }

    private void excluirUsers() {
        Object[] options = {"Sim", "N„o"};
        int exUser = JOptionPane.showOptionDialog(null, "Deseja realmente excluir o registro?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (exUser == 0) {
            objContDao.excluir(textCpf.getText());
            camposBotoesInicioCadastro();
            //this.carregarUsers();
        }
    }

    private void pesquisarUsers() {
        // executa o mÈtodo setcpf para preencher o cpf
        objMod.setCpf(textCpf.getText());

        // executa o mÈtodo buscar e coloca os registros dentro
        // do ResultSet rs
        conecta.rs = objContDao.buscar(objMod);
        try {
            if (conecta.rs.next()) {
                // se o registro foi encontrado preenche os campos do formul·rio usu·rios
                cmbPerfil.setSelectedItem(conecta.rs.getString("perfil"));
                textNome.setText(conecta.rs.getString("nome"));
                textCelular.setText(conecta.rs.getString("celular"));
                textEmail.setText(conecta.rs.getString("email"));
                textSenha.setText(conecta.rs.getString("senha"));
                textRua.setText(conecta.rs.getString("rua"));
                textNumRua.setText(conecta.rs.getString("numero"));
                textComplemento.setText(conecta.rs.getString("complemento"));
                textBairro.setText(conecta.rs.getString("bairro"));
                textCidade.setText(conecta.rs.getString("cidade"));
                textEstado.setText(conecta.rs.getString("estado"));

                btnUserNew.setEnabled(true);
                btnUserRegister.setEnabled(false);
                btnUserSearch.setEnabled(false);
                btnUserEdit.setEnabled(true);
                btnUserDel.setEnabled(true);

            } else {
                Object[] options = {"Sim", "N„o"};
                int exUser = JOptionPane.showOptionDialog(null, "Usu·rio n„o cadastrado!\nDeseja fazer o cadastro?", "Aviso",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                        null, options, options[0]);
                if (exUser == 0) {
                    todosCamposAtivos();
                    botoesBtnUserNew();
                    textCpf.grabFocus();

                    btnUserSearch.setEnabled(false);
                    //this.carregarUsers();
                }
                limparCampos();
                textCpf.grabFocus();
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    public void limparCampos() {
        textCpf.setText(null); //limpar
        textNome.setText(null); // limpar
        textCelular.setText(null); // limpar
        textEmail.setText(null); // limpar
        textSenha.setText(null); // limpar        
        textRua.setText(null); // limpar
        textNumRua.setText(null); // limpar
        textComplemento.setText(null); // limpar
        textBairro.setText(null); // limpar
        textCidade.setText(null); // limpar
        textEstado.setText(null); // limpar
    }

    public void todosCamposBotoesAtivos() {
        //campos
        todosCamposAtivos();
        //botıes
        todosBotoesAtivos();

        textCpf.grabFocus(); //coloca o cursor no campo cpf
    }

    public void camposBotoesInicioCadastro() {
        limparCampos();
        //campos
        textCpf.setEnabled(false);
        cmbPerfil.setEnabled(false);
        textNome.setEnabled(false);
        textCelular.setEnabled(false);
        textEmail.setEnabled(false);
        textSenha.setEnabled(false);
        textRua.setEnabled(false);
        textNumRua.setEnabled(false);
        textComplemento.setEnabled(false);
        textBairro.setEnabled(false);
        textCidade.setEnabled(false);
        textEstado.setEnabled(false);

        //botıes
        btnUserNew.setEnabled(true);
        btnUserRegister.setEnabled(false);
        btnUserSearch.setEnabled(false);
        btnUserEdit.setEnabled(false);
        btnUserDel.setEnabled(false);
    }

    public void todosCamposAtivos() {
        textCpf.setEnabled(true);
        cmbPerfil.setEnabled(true);
        textNome.setEnabled(true);
        textCelular.setEnabled(true);
        textEmail.setEnabled(true);
        textSenha.setEnabled(true);
        textRua.setEnabled(true);
        textNumRua.setEnabled(true);
        textComplemento.setEnabled(true);
        textBairro.setEnabled(true);
        textCidade.setEnabled(true);
        textEstado.setEnabled(true);
    }

    public void todosBotoesAtivos() {
        btnUserNew.setEnabled(true);
        btnUserRegister.setEnabled(true);
        btnUserSearch.setEnabled(true);
        btnUserEdit.setEnabled(true);
        btnUserDel.setEnabled(true);
    }

    public void botoesBtnUserNew() {
        btnUserNew.setEnabled(true);
        btnUserRegister.setEnabled(true);
        btnUserSearch.setEnabled(true);
        btnUserEdit.setEnabled(false);
        btnUserDel.setEnabled(false);
    }

    public void botoesBtnUserRegister() {
        btnUserNew.setEnabled(true);
        btnUserRegister.setEnabled(true);
        btnUserSearch.setEnabled(false);
        btnUserEdit.setEnabled(false);
        btnUserDel.setEnabled(false);
    }

    public void botoesBtnUserEdit() {
        btnUserNew.setEnabled(false);
        btnUserRegister.setEnabled(false);
        btnUserSearch.setEnabled(false);
        btnUserEdit.setEnabled(true);
        btnUserDel.setEnabled(true);
    }
    
}
