package view;

import controller.UsuarioDaoProj;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UsuarioProj;

/**
 *
 * @author oem
 */
public class FormCadRefencia extends javax.swing.JFrame {

    /**
     * Creates new form FormCli
     */
    public FormCadRefencia() {
        initComponents();
        //desativa edição dos campos ao entrar              
        cmbTipoUsers.setEnabled(false);
        textNome.setEnabled(false);
        textEmail.setEnabled(false);
        textCpf.setEnabled(false);
        textCelular.setEnabled(false);
        textLogin.setEnabled(false);
        textSenha.setEnabled(false);

        //ativa os botões ao entrar 
        btnNovo.setEnabled(false);
        btnCadastrar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnSair.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoUsers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        textCelular = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textSenha = new javax.swing.JPasswordField();
        btnNovo = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 68, 111));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 60, 0), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(715, 265));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><font size = 6><b><u>Usuários - Cadastro</b></u></font></html>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 55, -1, -1));
        jPanel1.add(textNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 340, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TIPO DE USUÁRIO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 55, -1, -1));

        cmbTipoUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTipoUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 144, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL:");
        jLabel3.setRequestFocusEnabled(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 105, -1, -1));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        jPanel1.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 340, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF: (Campo de pesquisa)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 155, -1, -1));

        try {
            textCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(textCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CELULAR:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 155, -1, -1));

        try {
            textCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(textCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGIN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 205, -1, -1));
        jPanel1.add(textLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SENHA:");
        jLabel5.setRequestFocusEnabled(false);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 205, -1, -1));
        jPanel1.add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 220, 110, -1));

        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 25));
        btnNovo.getAccessibleContext().setAccessibleDescription("");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 25));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 25));

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, 25));

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 25));

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 90, 25));

        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(250, 0, 0));
        btnInicio.setText("INÍCIO");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, 280));

        jPanel2.setBackground(new java.awt.Color(255, 60, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCliente.setAutoCreateRowSorter(true);
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "CPF", "Celular", "IDNivel", "Login", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setColumnSelectionAllowed(true);
        tblCliente.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblCliente);
        tblCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setResizable(false);
            tblCliente.getColumnModel().getColumn(1).setResizable(false);
            tblCliente.getColumnModel().getColumn(2).setResizable(false);
            tblCliente.getColumnModel().getColumn(3).setResizable(false);
            tblCliente.getColumnModel().getColumn(4).setResizable(false);
            tblCliente.getColumnModel().getColumn(5).setResizable(false);
            tblCliente.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 700, 210));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 721, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.formWindowOpened();
    }//GEN-LAST:event_formWindowOpened

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        this.cadastrarUsers();
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.sairUsers();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.novoUsers();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.pesquisarUsers();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluirUsers();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.btnInicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadRefencia().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbTipoUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCliente;
    private javax.swing.JFormattedTextField textCelular;
    private javax.swing.JFormattedTextField textCpf;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables

    private void formWindowOpened() {
        DefaultComboBoxModel obj;
        obj = (DefaultComboBoxModel) this.cmbTipoUsers.getModel();
        obj.removeAllElements();
        obj.addElement("");
        obj.addElement("Administrador");
        obj.addElement("Vendedor");
        obj.addElement("Cliente");
        this.carregarUsers();
    }

    //Funções para os botões - INÍCIO
    private void novoUsers() {
        //ativa os campos
        this.limparCampos();
        this.todosCamposAtivos();

        //ativa os botões 
        btnNovo.setEnabled(true);
        btnCadastrar.setEnabled(true);
        btnSair.setEnabled(true);
        btnPesquisar.setEnabled(true);

        //desativa os botões        
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }

    private void cadastrarUsers() {
        if (this.textNome.getText().equals("") || this.textEmail.getText().equals("") || this.textCpf.getText().equals("")
                || this.textCelular.getText().equals("") || this.cmbTipoUsers.getSelectedIndex() == 0
                || this.textLogin.getText().equals("") || this.textSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo obrigatório não preenchido");

        } else {

            DefaultTableModel MdlTableCli = (DefaultTableModel) this.tblCliente.getModel();
            Object[] linhas = {this.textNome.getText(), this.textEmail.getText(), this.textCpf.getText(),
                this.textCelular.getText(), this.cmbTipoUsers.getSelectedIndex(), this.textLogin.getText(), this.textSenha.getText()};
            MdlTableCli.addRow(linhas);
            //Instancia a Classe "UsuarioProj" e cria o objeto "Lu" - Pacote "Model"
            UsuarioProj cad = new UsuarioProj();

            /*usa o objeto "Lu" para adiconar os valores na classe "UsuarioProj" - Pacote "Model"*/
            cad.setNome(this.textNome.getText());
            cad.setEmail(this.textEmail.getText());
            cad.setCpf(this.textCpf.getText());
            cad.setCelular(this.textCelular.getText());
            cad.setIdNivel(this.cmbTipoUsers.getSelectedIndex());
            cad.setLogin(this.textLogin.getText());
            cad.setSenha(this.textSenha.getText());

            //Instancia a Classe "UsuarioDaoProj"
            UsuarioDaoProj u1 = new UsuarioDaoProj();
            //executa a função "incluir" da classe "UsuarioDaoProj"
            u1.incluir(cad);

            cmbTipoUsers.setEnabled(true);
            textNome.setEnabled(true);
            textEmail.setEnabled(true);
            textCpf.setEnabled(true);
            textCelular.setEnabled(true);
            textLogin.setEnabled(true);
            textSenha.setEnabled(true);

            //ativa os botões 
            btnNovo.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnSair.setEnabled(true);

            //desativa os botões 
            btnCadastrar.setEnabled(true);
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);

            this.limparCampos();
            this.textNome.grabFocus(); //coloca o cursor no campo nome  
        }
    }

    private void excluirUsers() {
        UsuarioDaoProj u = new UsuarioDaoProj();
        u.excluir(textCpf.getText());
        this.limparCampos();
        this.textNome.grabFocus(); //coloca o cursor no campo nome
        this.carregarUsers();
    }

    private void pesquisarUsers() {
        // instancia a classe UsuarioProj model
        UsuarioProj obj = new UsuarioProj();
        // executa o método setcpf para preencher o cpf
        obj.setCpf(this.textCpf.getText());
        // instancia o objeto Controller UsarioDaoProj
        UsuarioDaoProj u1 = new UsuarioDaoProj();
        // executa o método buscar e coloca os registros dentro
        // do ResultSet resul
        ResultSet resul = u1.buscar(obj);
        try {
            if (resul.next()) {
                // se o registro foi encontrado preenche os campos do formulário usuários
                this.textNome.setText(resul.getString("nome"));
                this.textEmail.setText(resul.getString("email"));
                this.textCelular.setText(resul.getString("celular"));
                this.cmbTipoUsers.setSelectedIndex(resul.getInt("idnivel"));
                this.textLogin.setText(resul.getString("login"));
                this.textSenha.setText(resul.getString("senha"));

                //ativa os botões 
                btnExcluir.setEnabled(true);
                btnSair.setEnabled(true);
                btnPesquisar.setEnabled(true);
                btnNovo.setEnabled(true);                

                //desativa os botões
                btnCadastrar.setEnabled(false);
                btnAlterar.setEnabled(false);                

            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.textCpf.grabFocus();
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    private void sairUsers() {
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente sair do sistema?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (i == 0) {
            dispose();
        }
    }
    //Funções para os botões - FIM

    private void carregarUsers() {
        UsuarioDaoProj u1 = new UsuarioDaoProj();
        // apagar todas as linhas do Jtable
        while (tblCliente.getModel().getRowCount() > 0) {
            ((DefaultTableModel) tblCliente.getModel()).removeRow(0);
        }
        try {
            ResultSet todos = u1.buscartodos();
            DefaultTableModel tab = (DefaultTableModel) this.tblCliente.getModel();

            while (todos.next()) {
                Object[] linha = {
                    todos.getString("nome"),
                    todos.getString("email"), todos.getString("cpf"),
                    todos.getString("celular"), todos.getInt("idNivel"),
                    todos.getString("login"), todos.getString("senha")};
                tab.addRow(linha);
            }
            todos.close();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    public void limparCampos() {
        this.cmbTipoUsers.setSelectedIndex(0); // limpar        
        this.textNome.setText(""); // limpar        
        this.textEmail.setText(""); // limpar
        this.textCpf.setText(""); //limpar
        this.textCelular.setText(""); // limpar
        this.textLogin.setText(""); // limpar
        this.textSenha.setText(""); // limpar
    }

    public void todosCamposAtivos() {
        cmbTipoUsers.setEnabled(true);
        textNome.setEnabled(true);
        textEmail.setEnabled(true);
        textCpf.setEnabled(true);
        textCelular.setEnabled(true);
        textLogin.setEnabled(true);
        textSenha.setEnabled(true);

        this.textNome.grabFocus(); //coloca o cursor no campo nome
    }

    private void btnInicio() {
        FormLogin dialog = new FormLogin(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

        cmbTipoUsers.setEnabled(true);
        textNome.setEnabled(true);
        textEmail.setEnabled(true);
        textCpf.setEnabled(true);
        textCelular.setEnabled(true);
        textLogin.setEnabled(true);
        textSenha.setEnabled(true);

        //ativa os botões ao entrar 
        btnNovo.setEnabled(true);
        btnSair.setEnabled(true);
        btnPesquisar.setEnabled(true);

        //desativa os botões ao entrar
        btnInicio.setEnabled(false);
        btnCadastrar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }
}
