package view;

import controller.ConectarDaoDefNew;
import controller.UsuarioDaoDefNew;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author José
 */
public class NewTelaLogin extends javax.swing.JFrame {    
    ConectarDaoDefNew conecta = new ConectarDaoDefNew(); //instancia a classe ConectarDaoDefNew
    UsuarioDaoDefNew objContDao = new UsuarioDaoDefNew(); //instancia a classe UsuarioDaoDefNew

    /**
     * Creates new form TelaLogin
     */
    public NewTelaLogin() {
        initComponents();
        inserirIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleCadastro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSairLogin = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDRL Materiais de Construção - Login");
        setBackground(new java.awt.Color(0, 68, 111));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(344, 201));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCadastro.setText("<html><font size = 6><b><u>Login</b></u></font></html>");
        lblTitleCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTitleCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jPanel1.setBackground(new java.awt.Color(0, 68, 111));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 60, 0), 5));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSairLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairLogin.setText("Sair");
        btnSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnSairLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 220, 63, -1));

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 220, 70, -1));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 220, 70, -1));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 160, 245, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 143, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 90, 245, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 73, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        btnLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        btnLimpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairLoginActionPerformed
        btnSairLogin();
    }//GEN-LAST:event_btnSairLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSairLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitleCadastro;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void btnLogin() {
        String login = txtUsuario.getText();
        String captura = new String(txtSenha.getPassword()); //modo seguro de capturar senha
        String senha = captura;
       
        try {

            conecta.rs = objContDao.validarLogin(login, senha);
            if (conecta.rs.next() || (login.equals("textUsuario")
                    && senha.equals("textSenha"))) {
                String perfil = conecta.rs.getString(2);
                //System.out.println(perfil);

                if (perfil.equals("Administrador")) {
                    NewTelaPrincipal tela = new NewTelaPrincipal();
                    tela.setVisible(true);
                    //ativa o menu cadastro na Tela Principal
                    NewTelaPrincipal.menCad.setEnabled(true);
                    //Pega o "nome" do "user no DB" e troca pelo conteúdo da label "lblUsuario"
                    NewTelaPrincipal.lblUsuario.setText(conecta.rs.getString(3));
                    //Pega o "perfil" do "user no DB" e troca pelo conteúdo da label "lblPerfilUser"
                    NewTelaPrincipal.lblPerfilUser.setText(conecta.rs.getString(2));
                    //Adiciona uma cor no contéudo da "lblPerfilUser"
                    NewTelaPrincipal.lblPerfilUser.setForeground(Color.red);

                    dispose();
                    conecta.rs.close(); //fecha a conexão
                } else {
                    NewTelaPrincipal tela = new NewTelaPrincipal();
                    tela.setVisible(true);
                    NewTelaPrincipal.lblUsuario.setText(conecta.rs.getString(3));
                    NewTelaPrincipal.lblPerfilUser.setText(conecta.rs.getString(2));
                    NewTelaPrincipal.lblPerfilUser.setForeground(Color.blue);

                    dispose();
                    conecta.rs.close(); //fecha a conexão
                }

            } else {
                JOptionPane.showMessageDialog(null,
                        "Ususário ou Senha Inválidos!", "Erro de Operação",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    private void btnLimpar() {
        this.txtUsuario.setText(null); // limpar
        this.txtSenha.setText(null); // limpar
        this.txtUsuario.grabFocus(); //coloca o cursor no campo login
    }

    private void btnSairLogin() {
        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Aviso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (i == 0) {
            //dispose();
            System.exit(0);
        }
    }
    
    //DIVERSOS
    private void inserirIcon() {        
            URL localImagen = getClass().getResource("/image/BackgroundIcon48x48.png");
            Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(localImagen);
            this.setIconImage(iconeTitulo);        
    }   
}
